name: Auto Deploy to Vercel

on:
  workflow_call:
    inputs:
      exclude-authors:
        description: 'GitHub usernames to exclude from auto-deploy (comma-separated)'
        required: false
        default: 'github-actions[bot]'
        type: string
    secrets:
      VERCEL_DEPLOY_HOOK:
        description: 'Vercel Deploy Hook URL'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Auto Deploy
    if: |
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main' &&
      !contains(inputs.exclude-authors, github.actor)
    
    steps:
      - name: Deploy to Vercel
        run: |
          echo "Auto-deploying changes from ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          
          curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK }}" \
            -H "Content-Type: application/json" \
            -d '{
              "ref": "main",
              "actor": "${{ github.actor }}",
              "repository": "${{ github.repository }}",
              "timestamp": "'$(date -Iseconds)'"
            }'
          
          echo "Deployment triggered!"
          echo "Check status: https://vercel.com/dashboard"
